version: '2.3'

services:
    generic-cpu:
      image: vykozlov/deep-oc-generic-dev:cpu
      # if 'docker-compose run' is used
      # do not forget '--service-ports'!
      ports:
        - 5000:5000
        - 8888:8888
      entrypoint: ["/run_jupyter.sh", "--allow-root"]

    generic-gpu:
      image: vykozlov/deep-oc-generic-dev
      runtime: nvidia
      ports:
        - 5000:5000
        - 8888:8888
      entrypoint: ["/run_jupyter.sh", "--allow-root"]

    generic-cpu-rclone:
      extends:
        service: generic-cpu
      volumes:
        - $HOME/.config/rclone:/root/.config/rclone
      environment:
        - RCLONE_CONFIG=/root/.config/rclone.conf
        # can also specify jupyterPASSWORD e.g.:
        # - jupyterPASSWORD=some_password
        - jupyterPASSWORD=rand0m%pass

