version: '2.3'

# if 'docker-compose run' is used
# do not forget '--service-ports'!
services:
    generic-cpu:
      image: ai4oshub/ai4os-dev-env:latest
      ports:
        - 5000:5000
        - 6006:6006
        - 8888:8888
      entrypoint: ["deep-start", "-j"]

    generic-cpu-vscode:
      image: ai4oshub/ai4os-dev-env:latest
      ports:
        - 5000:5000
        - 6006:6006
        - 8888:8888
      entrypoint: ["deep-start", "-s"]

    generic-gpu:
      image: ai4oshub/ai4os-dev-env:latest-gpu
      runtime: nvidia
      ports:
        - 5000:5000
        - 6006:6006
        - 8888:8888
      entrypoint: ["deep-start", "-j"]

    generic-gpu-vscode:
      image: ai4oshub/ai4os-dev-env:latest-gpu
      runtime: nvidia
      ports:
        - 5000:5000
        - 6006:6006
        - 8888:8888
      entrypoint: ["deep-start", "-s"]

    generic-cpu-rclone:
      extends:
        service: generic-cpu
      volumes:
        - $HOME/.config/rclone:/srv/.rclone
      environment:
        - RCLONE_CONFIG=/srv/.rclone/rclone.conf

